Refacted karpov
ahbpp/smart-home-2019 pull request #1
Opened 2019-03-06 17:31 UTC by ahbpp

Отредактировал код. Вроде даже все неплохо выглядит .

P.S. Я случайно первый pull-request в ваш master сделал 😬

2019-03-07 22:18 UTC, iagoshkov requested changes
Переделайте в соответствии с замечаниями. Уберите из git все бинарные файлы, порождаемые в процессе сборки (*.class файлы).
Еще лучше и всякие ide-specific файлы тоже. Типа .kotlin_module и т.п.

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        runProcessors(smartHome, event, eventProcessors);
Очень странный метод - почему мы первый event передаем в него как параметр, а потом следующие event-ы уже внутри генерируем через вызовы EventSensorGetter?
Сделайте чтобы все внутри генерировалось.

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/CommandSender.java
> +    public void sendMessage(SensorCommand command) {
Лучше так и назвать метод - sendCommand. Чтобы одна вещь везде называлась одним именем - Command. А не где-то command, а где-то message.

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Door.java
> +    public boolean equalId(SensorEvent event) {
Плохая зависимость - у нас была доменная модель SmartHome которая не знала ничего про события и их обработчики. И это было хорошо. Т.к. модель дома - абстракция, а события - уже ближе к деталям реализации. Мы раньше могли модель дома использовать в другом контексте (в другом, похожем, приложении), в котором например нет событий вообще. Теперь мы этого не можем, т.к. у нас модель SmartHome зависит от SensorEvent. Мы этим увеличили coupling.
Избавьтесь от этой зависимости.

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +    void runEvent(SensorEvent event, SmartHome smartHome);
Почему метод runEvent? Мы же его не запускаем, а обрабатываем.
Если уж EventProcessor, то самое просто и логичное название метода - processEvent

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEvent event = EventSensorGetter.getNextSensorEvent();
Нарушен OCP.
Как быть, когда мы захотим EventSensorGetter заменить на реальный класс, который будет от сенсоров события получать?
Тут нужно сделать интерфейс + реализацию, также как SmartHomeJsReader.

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Light.java
> +    public boolean equalId(SensorEvent event) { return this.getId().equals(event.getObjectId()); }
Замечание аналогичное Door. Лишний coupling.
Самый простой способ от него избавиться - передавать в метод минимум необходимой информации - не сам SensorEvent, а, например, только String id.

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void turnOffLight() {
Опять лишний coupling. Теперь SmartHome "знает" (зависит от) CommandSender.
Это деталь. Нарушение dependency inversion principle.
Абстрактная модель дома зависит от деталей работы с сенсорами. Этой зависимости быть не должно.
Подумайте как переделать.

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeCommandSender.java
> +    void sendMessage(SensorCommand command);
better sendCommand

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeJsReader.java
> +    public SmartHome ReadSmartHome() throws IOException {
В java названия методов начинаются с маленькой буквы

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHomePrinter.java
> +public interface SmartHomePrinter {
Почему SmartHomePrinter - он печатает дом? Или сообщения?
MessagerPrinter?

2019-03-07 22:18 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeReader.java
> +    SmartHome ReadSmartHome() throws IOException;
с маленькой буквы

2019-03-11 17:28 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/SmartHomeReader.java
> +    SmartHome ReadSmartHome() throws IOException;
Случчайно получилось)

2019-03-11 17:28 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/SmartHomePrinter.java
> +public interface SmartHomePrinter {
Исправил

2019-03-11 17:28 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/SmartHomeCommandSender.java
> +    void sendMessage(SensorCommand command);
Исправил

2019-03-11 17:29 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void turnOffLight() {
Сделал отдельный метод для light

2019-03-11 17:29 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/Light.java
> +    public boolean equalId(SensorEvent event) { return this.getId().equals(event.getObjectId()); }
Исправил

2019-03-11 17:29 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEvent event = EventSensorGetter.getNextSensorEvent();
Исправил и добавил интерфейс

2019-03-11 17:30 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +    void runEvent(SensorEvent event, SmartHome smartHome);
Исправил

2019-03-11 17:30 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/Door.java
> +    public boolean equalId(SensorEvent event) {
Исправил

2019-03-11 17:30 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/CommandSender.java
> +    public void sendMessage(SensorCommand command) {
Исправил

2019-03-11 17:30 UTC, ahbpp commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        runProcessors(smartHome, event, eventProcessors);
Убрал метод, теперь вышлядит все логичнее

2019-03-11 18:39 UTC, iagoshkov approved these changes
Можно вмержить, но зависимость модели дома от Command осталась - подумайте как исправить в рамках второго ДЗ.

2019-03-11 18:39 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void turnOffLight() {
Это не решило проблемы ))
Все равно модель дома зависит от Command - а раньше этого не было.
Подумайте как исправить в рамках второго ДЗ, пускай пока так останется.

2019-03-13 20:28 UTC, merged